baseURL = 'https://liasop.github.io/site/'
languageCode = 'en-us'
title = 'Lia Chin-Purcell'
publishDir = 'docs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[imaging]
  quality = 85
  resampleFilter = "Lanczos"
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    includeFields = ".*"
